// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhAGPTx0x_aQCpfHiEus3dfiZF-FrhmIw',
    appId: '1:981569090691:web:a025022493d960358cd7b6',
    messagingSenderId: '981569090691',
    projectId: 'tuscanchas-app',
    authDomain: 'tuscanchas-app.firebaseapp.com',
    storageBucket: 'tuscanchas-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgfWGkoM-dzlQ8VWnJHjcTs5jYHnBJgXM',
    appId: '1:981569090691:android:0fee247ef1f005138cd7b6',
    messagingSenderId: '981569090691',
    projectId: 'tuscanchas-app',
    storageBucket: 'tuscanchas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBNnNsbYE3OMa1a4DQbIqennyp_815Eg',
    appId: '1:981569090691:ios:4e650ecec975db268cd7b6',
    messagingSenderId: '981569090691',
    projectId: 'tuscanchas-app',
    storageBucket: 'tuscanchas-app.appspot.com',
    iosBundleId: 'com.example.tusCanchasAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBNnNsbYE3OMa1a4DQbIqennyp_815Eg',
    appId: '1:981569090691:ios:b75d68f521a5717e8cd7b6',
    messagingSenderId: '981569090691',
    projectId: 'tuscanchas-app',
    storageBucket: 'tuscanchas-app.appspot.com',
    iosBundleId: 'com.example.tusCanchasAppV2.RunnerTests',
  );
}
